# Generated by Django 4.2.2 on 2023-06-16 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastr_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Usuario',
        ),
    ]
